#!/bin/sh
#
#   Copyright 2012 Jonathan M. Reid. See LICENSE.txt
#   Created by: Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#

source envcov.sh

remove_old_report()
{
    pushd ${BUILT_PRODUCTS_DIR}
    if [ -e lcov ]; then
        rm -r lcov
    fi
    popd
}

enter_lcov_dir()
{
    cd ${BUILT_PRODUCTS_DIR}
    mkdir lcov
    cd lcov
}

gather_coverage()
{
    "${LCOV}" --capture -b "${SRCROOT}" -d "${OBJ_DIR}" -o ${LCOV_INFO}
}

exclude_data()
{
    "${LCOV}" --remove ${LCOV_INFO} "/Applications/Xcode.app/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    "${LCOV}" --remove ${LCOV_INFO} "main.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    # Remove other patterns here...
    "${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/cocos2d-iphone/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    "${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/libs/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/AppDelegate.h" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/AppDelegate.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/IntroLayer.h" -d "${OBJ_DIR}" -o $
{LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/IntroLayer.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/Explosion.h" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/Explosion.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/GCHelper.h" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/GCHelper.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/GameMenuScene.h" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/GameMenuScene.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/ScoreScene.h" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/ScoreScene.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/HowToPlayScene.h" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/HowToPlayScene.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/Supporting Files/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/MultiPlayerScene.h" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/LevelSelectScene.h" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/LevelSelectScene.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
"${LCOV}" --remove ${LCOV_INFO} "SmashingWord_me/SinglePlayerScene.h" -d "${OBJ_DIR}" -o ${LCOV_INFO}


}

generate_report()
{
    "${LCOV_PATH}/genhtml" --output-directory . ${LCOV_INFO}
    open index.html
}

remove_old_report
enter_lcov_dir
gather_coverage
exclude_data
generate_report
